import { Injectable } from "@angular/core";
import { VoucherTypeEnum } from "../../interfaces/TrnMain";

@Injectable()
export class UserWiseTransactionFormConfigurationService {

    public transactionGridDetails = [
        {
            formName: "Sales Order",
            voucherType: VoucherTypeEnum.SalesOrder,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "salesman", SHOWFOCUS: true },
                { LABELVALUE: 'Disc2 %', HEADERKEY: 'DISCOUNT2_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount2", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Disc2 Amt', HEADERKEY: 'DISCOUNT2_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discount2Amt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Salesman', HEADERKEY: 'SALESMAN_EDITABLE', CONTROLVALUE: true, CONTROLID: "salesman", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: true },
                { LABELVALUE: 'Promotion', HEADERKEY: 'PROMOTION', CONTROLVALUE: true, CONTROLID: "promotion", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: false },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true },
            ]
        },
        {
            formName: "Proforma Invoice",
            voucherType: VoucherTypeEnum.PerformaSalesInvoice,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Disc2 %', HEADERKEY: 'DISCOUNT2_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount2", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Disc2 Amt', HEADERKEY: 'DISCOUNT2_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discount2Amt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Salesman', HEADERKEY: 'SALESMAN_EDITABLE', CONTROLVALUE: true, CONTROLID: "salesman", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: true },
                { LABELVALUE: 'Promotion', HEADERKEY: 'PROMOTION', CONTROLVALUE: true, CONTROLID: "promotion", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: false },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true },
            ]
        },
        {
            formName: "Delivery Challan",
            voucherType: VoucherTypeEnum.DeliveryChallaan,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Disc2 %', HEADERKEY: 'DISCOUNT2_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount2", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Disc2 Amt', HEADERKEY: 'DISCOUNT2_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discount2Amt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Salesman', HEADERKEY: 'SALESMAN_EDITABLE', CONTROLVALUE: true, CONTROLID: "salesman", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: true },
                { LABELVALUE: 'Promotion', HEADERKEY: 'PROMOTION', CONTROLVALUE: true, CONTROLID: "promotion", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: false },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true },
            ]
        },
        {
            formName: "Sales Invoice",
            voucherType: VoucherTypeEnum.TaxInvoice,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "salesman", SHOWFOCUS: true },
                { LABELVALUE: 'Disc2 %', HEADERKEY: 'DISCOUNT2_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount2", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Disc2 Amt', HEADERKEY: 'DISCOUNT2_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discount2Amt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Salesman', HEADERKEY: 'SALESMAN_EDITABLE', CONTROLVALUE: true, CONTROLID: "salesman", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: true },
                { LABELVALUE: 'Promotion', HEADERKEY: 'PROMOTION', CONTROLVALUE: true, CONTROLID: "promotion", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true },
            ]
        },
        {
            formName: "Credit Note",
            voucherType: VoucherTypeEnum.CreditNote,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "salesman", SHOWFOCUS: true },
                { LABELVALUE: 'Disc2 %', HEADERKEY: 'DISCOUNT2_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount2", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Disc2 Amt', HEADERKEY: 'DISCOUNT2_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discount2Amt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Salesman', HEADERKEY: 'SALESMAN_EDITABLE', CONTROLVALUE: true, CONTROLID: "salesman", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: true },
                { LABELVALUE: 'Promotion', HEADERKEY: 'PROMOTION', CONTROLVALUE: true, CONTROLID: "promotion", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: false },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true },
            ]
        },
        {
            formName: "Purchase Order",
            voucherType: VoucherTypeEnum.PurchaseOrder,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Purchase Invoice",
            voucherType: VoucherTypeEnum.Purchase,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "BasePrimaryDiscount", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "BaseSecondaryDiscount", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true },
                { LABELVALUE: 'Taxable', HEADERKEY: 'TAXABLEAMT_HEADER', CONTROLVALUE: true, CONTROLID: "TAXABLEAMT_HEADER", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false }

            ]
        },
        {
            formName: "Debit Note",
            voucherType: VoucherTypeEnum.DebitNote,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Material Receipt",
            voucherType: VoucherTypeEnum.MaterialReceipt,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Material Receipt",
            voucherType: VoucherTypeEnum.StockIssue,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Material Receipt",
            voucherType: VoucherTypeEnum.StockSettlement,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Material Receipt",
            voucherType: VoucherTypeEnum.StockSettlementEntryApproval,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Material Receipt",
            voucherType: VoucherTypeEnum.BranchTransferIn,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Material Receipt",
            voucherType: VoucherTypeEnum.BranchTransferOut,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        },
        {
            formName: "Material Receipt",
            voucherType: VoucherTypeEnum.OpeningStockBalance,
            columns: [
                { LABELVALUE: 'Barcode', HEADERKEY: 'BARCODE_OPTION', CONTROLVALUE: true, CONTROLID: "barcodebilling", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Code', HEADERKEY: 'MCODE_HEADER', CONTROLVALUE: true, CONTROLID: "menucode", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Description', HEADERKEY: 'DESCA_HEADER', CONTROLVALUE: true, CONTROLID: "ITEMDESC", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'C.F.', HEADERKEY: 'CONFACTOR_HEADER', CONTROLVALUE: true, CONTROLID: "CF", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'BatchNo', HEADERKEY: 'BATCH_HEADER', CONTROLVALUE: true, CONTROLID: "batch", ISMANDATORY: false, FOCUSTO: "mfgdate", SHOWFOCUS: true },
                { LABELVALUE: 'MFG Dt', HEADERKEY: 'MFGDATE_HEADER', CONTROLVALUE: true, CONTROLID: "mfgdate", ISMANDATORY: false, FOCUSTO: "expdate", SHOWFOCUS: true },
                { LABELVALUE: 'Exp Dt', HEADERKEY: 'EXPDATE_HEADER', CONTROLVALUE: true, CONTROLID: "expdate", ISMANDATORY: false, FOCUSTO: "quantity", SHOWFOCUS: true },
                { LABELVALUE: 'Qty', HEADERKEY: 'QUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "quantity", ISMANDATORY: true, FOCUSTO: "freequantity", SHOWFOCUS: true },
                { LABELVALUE: 'Free Qty', HEADERKEY: 'FREEQUANTITY_HEADER', CONTROLVALUE: true, CONTROLID: "freequantity", ISMANDATORY: false, FOCUSTO: "alternateunit", SHOWFOCUS: true },
                { LABELVALUE: 'Packing', HEADERKEY: 'PACKING_HEADER', CONTROLVALUE: true, CONTROLID: "alternateunit", ISMANDATORY: true, FOCUSTO: "mrp", SHOWFOCUS: true },
                { LABELVALUE: 'MRP', HEADERKEY: 'MRP_HEADER', CONTROLVALUE: true, CONTROLID: "mrp", ISMANDATORY: true, FOCUSTO: "prateid", SHOWFOCUS: true },
                { LABELVALUE: 'Cost Price', HEADERKEY: 'COSTPRICE_HEADER', CONTROLVALUE: true, CONTROLID: "prateid", ISMANDATORY: false, FOCUSTO: "srateid", SHOWFOCUS: true },
                { LABELVALUE: 'Selling Price', HEADERKEY: 'SELLING_HEADER', CONTROLVALUE: true, CONTROLID: "srateid", ISMANDATORY: false, FOCUSTO: "discount", SHOWFOCUS: true },
                { LABELVALUE: 'Profit', HEADERKEY: 'PROFIT_HEADER', CONTROLVALUE: true, CONTROLID: "profit", ISMANDATORY: false, FOCUSTO: "", SHOFOCUS: false, SHOWFOCUS: true },
                { LABELVALUE: 'Disc%', HEADERKEY: 'DISCOUNT_PER_HEADER', CONTROLVALUE: true, CONTROLID: "discount", ISMANDATORY: false, FOCUSTO: "discountAmt", SHOWFOCUS: true },
                { LABELVALUE: 'Disc Amt', HEADERKEY: 'DISCOUNT_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "discountAmt", ISMANDATORY: false, FOCUSTO: "primarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'GST%', HEADERKEY: 'GST_PER_HEADER', CONTROLVALUE: true, CONTROLID: "gstper", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'GST TaxAmt', HEADERKEY: 'GST_AMT_HEADER', CONTROLVALUE: true, CONTROLID: "gstamt", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess %', HEADERKEY: 'CESS_PER', CONTROLVALUE: true, CONTROLID: "cessper", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Cess Amount', HEADERKEY: 'CESS_AMOUNT', CONTROLVALUE: true, CONTROLID: "cessamt", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'P Dis.%', HEADERKEY: 'PRIMARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "primarydiscountper", ISMANDATORY: false, FOCUSTO: "secondarydiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'P Dis.', HEADERKEY: 'PRIMARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BasePrimaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'S Dis.%', HEADERKEY: 'SECONDARY_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "secondarydiscountper", ISMANDATORY: false, FOCUSTO: "liquiditiondiscountper", SHOWFOCUS: true },
                { LABELVALUE: 'S Dis.', HEADERKEY: 'SECONDARY_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseSecondaryDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'L Dis.%', HEADERKEY: 'LIQUIDITION_DIS_PER_HEADER', CONTROLVALUE: true, CONTROLID: "liquiditiondiscountper", ISMANDATORY: false, FOCUSTO: "adjustment", SHOWFOCUS: true },
                { LABELVALUE: 'L Dis.', HEADERKEY: 'LIQUIDITION_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "BaseLiquiditionDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'OS Dis.', HEADERKEY: 'OTHER_DIS_HEADER', CONTROLVALUE: true, CONTROLID: "OtherDiscount", ISMANDATORY: false, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Adjusted Amt', HEADERKEY: 'ADJUSTMENT_HEADER', CONTROLVALUE: true, CONTROLID: "adjustment", ISMANDATORY: false, FOCUSTO: "remarks", SHOWFOCUS: true },
                { LABELVALUE: 'Net Amnt', HEADERKEY: 'NETAMOUNT_HEADER', CONTROLVALUE: true, CONTROLID: "netamount", ISMANDATORY: true, FOCUSTO: "", SHOWFOCUS: false },
                { LABELVALUE: 'Remarks', HEADERKEY: 'REMARKS_HEADER', CONTROLVALUE: true, CONTROLID: "remarks", ISMANDATORY: true, FOCUSTO: "BREAKROW", SHOWFOCUS: true }
            ]
        }
    ]






    resolveAndLoadConfiguration = (voucherType: VoucherTypeEnum) => {
        return this.transactionGridDetails.filter(x => x.voucherType == voucherType)[0];

    }
}