import { Routes, RouterModule, CanActivate } from '@angular/router';
import { ReportsComponent } from './Reports.component';
import { CanActivateTeam } from "../../common/services/permission/guard.service";
import { ReportMain } from './components/ReportMain/ReportMain';
import { Component } from '@angular/core';
import { CrateReportComponent } from '../ReportDialogs/crateReport/crateReport.component';
import { LoyaltyReport } from '../ReportDialogs/loyalty-report/loyalty-report.component';

const routes: Routes = [
    {

        path: '',
        component: ReportsComponent,
        children: [
            { path: 'reportmain', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'partialsalesbill', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'closingStock', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'SupplierWiseStock', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ClosingStockSummaryReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ClosingStockSummaryReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'StockandSalesCategorySummary', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'StockandSalesItemSummaryCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'StockandSalesItemSummary', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ShortExpiryReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'closingstockcentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'currentstockitemwisecentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'currentstockitemwisesummarycentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'GROSSMARGINREPORT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'GROSSMARGINREPORTMONTHWISE', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'billwiseitemsalesreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemwisesalesreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemwisesalescentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemwisecategorysalescentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'STOCKISSUEREPORT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'STOCKISSUEREPORTCENTRAL', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ShortExpiryReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'BESTBUYPRODUCTREPORT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'SLOWBUYPRODUCTREPORT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'BESTBUYCUSTOMERREPORT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'CUSTOMERITEMTRACKREPORT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'SalemanCommisionReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'proformadetailreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'proformasummaryreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseinvoicedetailreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'materialreceiptreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'MRvsPIReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'POvsSOReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'materialreceiptcentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'MRvsPIReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'IndentVSPOReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'POVSMRReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseinvoicedetailcentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseorderdetailreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseordercentraldetailreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'customerwiseitemsales', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'dailysalesreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'hoursalesreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'LoadSheetDetail', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'IndentReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'IndentCentralReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'BillWiseItemWiseSalesCentralReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'UserLoginDetailsCentralReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'HourlySalesItemwiseCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'SalesItemWiseSummaryCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'CategoryStockItemWiseSalesCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'AvailableStockForDay', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseRegisterReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'dailysalescentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'salesorder', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemMasterreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'PRICELIST', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'transferincentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'transferoutcentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'LOYALTYREPORT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'customerwiseloyalty', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'customerwiseloyaltycentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'customerwisedetailloyalty', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'couponcreationreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'coupondiscountreceivedreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'coupondiscountreceivedreportcentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'couponcreationsummaryreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'couponcreationreportsummarycentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'couponcreationreportcentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'customerwisedetailloyaltycentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'CustomerMasterReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'OUTLETLIST', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'SCHEMEMASTER', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'stockSettlementreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'StockSettlementReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemSchemeMasterreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemwisechannelmarginreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchasereturnreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'salesbillcancelreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'customerwisesalesreturnreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'dailycollectionreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'monthlycollectionreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'monthlycollectioncentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'dailycollectioncentralreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'GstSalesSummaryTaxSlabReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'GSTPurchaseSummaryTaxSlabReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'salesreturnreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'schemereport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseordersummary', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'POVSMRReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'IndentVSPOReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchasesummary', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'salesordersummary', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'salesreturnsummary', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemwisestockandsalessummary', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'TransactionReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseRegisterReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'salesRegisterReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'opening-stock-report', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'OpeningStockCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'mrp-change-report', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'audit-report', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'auditcentral-report', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseReturnSummaryReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'POvsPIReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'POvsPICentralReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'TransactionwiseStockReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'MocWiseSales', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'MonthWiseSales', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'holdbillreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'intransitreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemexpiryreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'IndentVsReplenishedReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'DeliveryStatusReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'itemexpiryreportcentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'agewiseexpiryReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'autodebitnoteraisedreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'erppireport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'erpsireport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'sovssi', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'sovspo', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'soerrorlogreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ordertransfer', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'supplierstockreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'povsintransit', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'povspivsintransit', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'delordstatusreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ordermestatus', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'transferin', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'TransferInCentralReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'TransferoutCentralReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'transferout', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'claimreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'erpSalesReturnReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'SALESRETURNREPORTCENTRAL', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'erpPurchaseReturnReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'claimandexpiryreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'PRvsSRreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'combopackconfigreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'areasalesourstandinreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'partyageoutstandingreconcillation', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'customerbillreminderreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'nontransactedpartyreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'salesmanecoreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'crateReport', component: CrateReportComponent, canActivate: [CanActivateTeam] },
            { path: 'ItemExpiryReport_Central', component: CrateReportComponent, canActivate: [CanActivateTeam] },
            { path: 'loyaltymasterreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'FASTMOVINGPRODUCT', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ItemCorelation', component: ReportMain, canActivate: [CanActivateTeam] },

            //CODE
            { path: 'ItemCorelationFiltered', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'HourSalesCentralReport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'purchaseMonthlyReport', component: ReportMain, canActivate: [CanActivateTeam] },
            {
                path: 'BestBuyProductReportCentral', component: ReportMain, canActivate: [CanActivateTeam]
            },
            { path: 'purchaseMonthlywiseSummaryReport', component: ReportMain, canActivate: [CanActivateTeam] },
            {
                path: 'currentstockcategorywisecentral', component: ReportMain, canActivate: [CanActivateTeam]
            },
            { path: 'couponmasterreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'couponmasterreportcentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'opticalreport', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'PurchaseSummaryCategoryReportCentral', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'OfferManagementReport', component: ReportMain, canActivate: [CanActivateTeam] },

            { path: 'SalesVsGRNAnalysis', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ItemTransactionHistory', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ItemTransactionHistoryStandAlone', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ExpectedPOVsActualPurchase', component: ReportMain, canActivate: [CanActivateTeam] },

            { path: 'SuggestedPOQtybasedonlastdaySale', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'FastMovingOutletWise', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'SlowMovingOutletWise', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'PushSalesItemList', component: ReportMain, canActivate: [CanActivateTeam] },
            { path: 'ItemSalesHistory', component: ReportMain, canActivate: [CanActivateTeam] },


        ]
    }
];

export const routing = RouterModule.forChild(routes);
