export class Company{
INITIAL:string;
NAME:string;
TELB:string;
ADDRESS:string;
TELA:string;
VAT:string;
EMAIL:String;
WEBSITE:String;
FBDATE:String;
FEDATE:String;
FBDATE_BS:String;
FEDATE_BS:String;
ISBRANCH:Number;
ID:String;
PhiscalID:string;
BRANCHID:string;
ADDRESS2:string;
POSTALCODE:string;
GSTNO:string;
STATE:string;
ORG_TYPE:string;
PLACE:string;
STATENAME:string;
PINCODE:string;
MERCHANTLEGALNAME:string;
CUSTOMERCODE:string;
COMPANYID:string;
CITY:string;
GSTTYPE:string;
PANNO:string;
CIN:string;
BankName:string;
AccountNo:string;
IFSCCode:string;
AcountHolder:string;
BankBranch:string;
Declaration:string;
LastYearTurnOver:number;
NonWorkingDays:string;
companycode:string;
COMPANYLIST:any;
FSSAI:string;
    DLNO1: any;
    DLNO2: any;
    DLNO3: any;
    DLNO4: any;

    }                               