export interface eway {
    version: string,
    billLists: billLists[],
}
export interface billLists {
    userGstin: string,
    supplyType: string,
    subSupplyType: number,
    docType: string,
    docNo: string,
    docDate: string,
    transType: Number,
    fromGstin: string,
    fromTrdName: string,
    fromAddr1: string,
    fromAddr2: string,
    fromPlace: string,
    fromPincode: string,
    fromStateCode: number,
    actualFromStateCode: number,
    toGstin: string,
    toTrdName: string,
    toAddr1: string,
    toAddr2: string,
    toPlace: string,
    toPincode: string,
    toStateCode: number,
    actualToStateCode: number,
    totalValue: number,
    cgstValue: number,
    sgstValue: number,
    igstValue: number,
    cessValue: number,
    TotNonAdvolVal: number,
    OthValue: number,
    transMode: number,
    transDistance: number,
    transporterName: string,
    transporterId: string,
    transDocNo: string,
    transDocDate: string,
    vehicleNo: string,
    vehicleType: string,
    totInvValue: number
    mainHsnCode: string,
    itemList: itemList[]
}
export interface itemList {
    itemNo: number,
    productName: string,
    productDesc: string,
    hsnCode: string,
    quantity: number,
    qtyUnit: string,
    taxableAmount: number,
    sgstRate: number,
    cgstRate: number,
    igstRate: number,
    cessRate: number,
    cessNonAdvol: number,
}
